### ISSUE TITLE
[FEATURE] Catch Us Up!

### ISSUE THREAD

**Issue by lectronyx** [Starfly-13/STARFLY-13#2]
## Name of feature:

Catch us up on Shiptest PRs as of 12/11/2023, minus removing the vineboom.

### Related Pull Request on other codebase:

https://mega.nz/file/qPgwAShK#yjE8sOeEAsDQLC7XQ5xuf27sRxC5pd0CLDZz3aLGJRs

### Additional Info:

Can't really say this is a lot of work. Just updating this branch, and then undoing a single PR.

**Comment by blinkdog** [comment]
@lectronyx Is https://github.com/shiptest-ss13/Shiptest/pull/2579 the PR that you want to revert after syncing?

**Comment by blinkdog** [comment]
From Discord discussion: #2579 is the correct PR, but we want to keep the `examine_block`, just revert the `sound/misc/compiler-stage2.ogg` back to `sound/misc/vinethud.ogg`.
